-- Neutralized: this migration originally mutated the published INC v1
-- definition's specification directly with an UPDATE, which bypassed the
-- catalog's real CreateDraft -> Validate -> Publish flow (immutable
-- manifest + checksum per version). INC v1 must stay exactly as inserted
-- by 000003_create_catalog_metamodel. The category/site/assetId fields
-- are instead introduced as INC v2, published through the real catalog
-- workflow (see the application bootstrap that seeds it on API startup).
--
-- If this migration already ran against a persistent dev volume before
-- this fix landed, INC v1's specification may already have been mutated
-- in that database. Because these are docker-entrypoint-initdb.d scripts
-- (they only run once, against an empty volume), editing this file does
-- not repair an already-initialized volume. For local dev, recreate it:
--   docker compose down -v && docker compose up -d postgres
-- This is safe: all data in this environment is disposable seed/demo data.
