import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiRequest } from '@/lib/apiClient';

type Item = { id: string; rating: string; status: string; question: string; answer: string; sources: { type: string; id: string }[]; comment?: string; created_at: string; classification?: string };
const classifications = ['knowledge_article', 'prompt_rule', 'ticket_data_gap', 'retrieval_tuning', 'no_action'];

export default function AssistantFeedback() {
  const [items, setItems] = useState<Item[]>([]); const [status, setStatus] = useState('open'); const [selected, setSelected] = useState<Item | null>(null); const [classification, setClassification] = useState('no_action'); const [note, setNote] = useState(''); const [error, setError] = useState('');
  const load = async () => { try { const data = await apiRequest<{items: Item[]}>(`/ia_advisor/admin/feedback?status=${status}`); setItems(data.items); setSelected(null); } catch { setError('No fue posible cargar la cola de feedback.'); } };
  useEffect(() => { void load(); }, [status]);
  const resolve = async (next: 'reviewed' | 'resolved') => { if (!selected) return; try { await apiRequest(`/ia_advisor/admin/feedback/${selected.id}`, { method: 'PATCH', body: JSON.stringify({ status: next, classification, resolution_note: note, promote_to_evaluation: false }) }); await load(); } catch { setError('No fue posible actualizar el reporte.'); } };
  return <main className="mx-auto max-w-6xl p-6 text-on-surface"><h1 className="text-2xl font-bold">Feedback del asistente</h1><p className="mt-1 text-sm text-on-surface-variant">Se revisa un turno y su evidencia; nunca se guarda ni se muestra la conversación completa.</p><div className="mt-5 flex gap-3"><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded border bg-surface-container p-2"><option value="open">Abiertos</option><option value="reviewed">Revisados</option><option value="resolved">Resueltos</option></select>{error && <span className="text-red-400">{error}</span>}</div><div className="mt-5 grid gap-5 md:grid-cols-2"><section className="space-y-3">{items.map((item) => <button type="button" key={item.id} onClick={() => { setSelected(item); setClassification(item.classification ?? 'no_action'); }} className="block w-full rounded-xl border border-border bg-surface-container p-4 text-left hover:border-cyan-400/50"><div className="text-xs text-cyan-300">{item.rating === 'useful' ? 'Útil' : 'No útil'} · {item.status}</div><p className="mt-2 line-clamp-2">{item.question}</p><p className="mt-1 line-clamp-2 text-sm text-on-surface-variant">{item.comment || item.answer}</p></button>)}{!items.length && <p className="text-on-surface-variant">No hay reportes en este estado.</p>}</section>{selected && <aside className="rounded-xl border border-border bg-surface-container p-5"><h2 className="font-bold">Evidencia del turno</h2><p className="mt-3 text-sm"><b>Pregunta:</b> {selected.question}</p><p className="mt-3 whitespace-pre-wrap text-sm"><b>Respuesta:</b> {selected.answer}</p><p className="mt-3 text-xs text-on-surface-variant">Fuentes: {selected.sources?.map((s) => `${s.type}/${s.id}`).join(', ') || 'sin fuentes'}</p><label className="mt-5 block text-sm">Clasificación<select value={classification} onChange={(e) => setClassification(e.target.value)} className="mt-1 block w-full rounded border bg-surface-container-low p-2">{classifications.map((v) => <option key={v}>{v}</option>)}</select></label><textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="Nota de revisión" className="mt-3 w-full rounded border bg-surface-container-low p-2" rows={3}/><div className="mt-4 flex gap-2"><button onClick={() => void resolve('reviewed')} className="rounded bg-surface-container-high px-3 py-2 text-sm">Marcar revisado</button><button onClick={() => void resolve('resolved')} className="rounded bg-cyan-400 px-3 py-2 text-sm text-slate-950">Resolver</button><Link to="/app/knowledge/new" state={{ feedback: selected }} className="rounded border px-3 py-2 text-sm">Abrir borrador KB</Link></div></aside>}</div></main>;
}
