import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { createDraft, publishDraft } from './api';

export default function KnowledgeEditor() {
  const navigate = useNavigate(); const [titulo, setTitulo] = useState(''); const [categoria, setCategoria] = useState(''); const [audiencia, setAudiencia] = useState('general'); const [etiquetas, setEtiquetas] = useState(''); const [contenido, setContenido] = useState(''); const [message, setMessage] = useState('');
  const guardar = async (publicar: boolean) => { try { const draft = await createDraft({ titulo, categoria, audiencia, etiquetas: etiquetas.split(',').map(x => x.trim()).filter(Boolean), contenido }); if (publicar) await publishDraft(draft.id); setMessage(publicar ? 'Enviado a publicación.' : 'Borrador guardado.'); } catch { setMessage('No tienes permiso o faltan campos obligatorios.'); } };
  return <div className="p-8 max-w-4xl space-y-4"><h1 className="text-3xl font-black text-on-surface">Nuevo manual</h1><input value={titulo} onChange={e => setTitulo(e.target.value)} placeholder="Título" className="w-full p-3 rounded-xl bg-surface-container-low border border-border" /><div className="grid grid-cols-2 gap-3"><input value={categoria} onChange={e => setCategoria(e.target.value)} placeholder="Categoría" className="p-3 rounded-xl bg-surface-container-low border border-border" /><select value={audiencia} onChange={e => setAudiencia(e.target.value)} className="p-3 rounded-xl bg-surface-container-low border border-border"><option value="general">General</option><option value="interno_it">Interno IT</option><option value="restringido">Restringido</option></select></div><input value={etiquetas} onChange={e => setEtiquetas(e.target.value)} placeholder="Etiquetas separadas por coma" className="w-full p-3 rounded-xl bg-surface-container-low border border-border" /><textarea value={contenido} onChange={e => setContenido(e.target.value)} placeholder="Contenido Markdown" rows={18} className="w-full p-3 rounded-xl bg-surface-container-low border border-border font-mono" /><div className="flex gap-3"><button onClick={() => guardar(false)} className="px-4 py-2 rounded-xl bg-surface-container border border-border">Guardar borrador</button><button onClick={() => guardar(true)} className="px-4 py-2 rounded-xl bg-cyan-500 text-black font-bold">Publicar</button><button onClick={() => navigate('/app/knowledge')} className="px-4 py-2">Cancelar</button></div>{message && <p className="text-on-surface-variant">{message}</p>}</div>;
}
